steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "$$GOOGLE_APPLICATION_CREDENTIALS_CONTENT" > /workspace/service-account-key.json
        export GOOGLE_APPLICATION_CREDENTIALS="/workspace/service-account-key.json"
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/react-app", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/react-app"]
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        export GOOGLE_APPLICATION_CREDENTIALS="/workspace/service-account-key.json"
        gcloud beta run deploy react-app --image gcr.io/$PROJECT_ID/react-app --region us-central1 --platform managed --allow-unauthenticated
